version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - php
      - npm
    restart: always
  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    restart: always
  
  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["/bin/sh", "-c", "npm install && npm run build"]
    working_dir: /var/www/html

  artisan:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    depends_on:
      - mysql
      - npm
    command: sh -c "php artisan optimize && php artisan view:cache && php artisan event:cache"

  composer:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    depends_on:
      - mysql
      - npm
    command: sh -c "composer install --optimize-autoloader --no-dev"
