version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - php
      - npm
      - composer
      - artisan
    restart: always
  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    restart: always
  
  npm:
    image: node:latest
    volumes:
      - ./src:/var/www/html
    entrypoint: ["/bin/sh", "-c", "npm install && npm run build"]
    working_dir: /var/www/html

  artisan:
    entrypoint: ["/bin/sh", "-c", "php artisan optimize && php artisan view:cache && php artisan event:cache"]
    working_dir: /var/www/html
    depends_on:
      - mysql

  composer:
    entrypoint: ["/bin/sh", "-c", "composer install --optimize-autoloader --no-dev"]
    working_dir: /var/www/html
